# Restore old style debuginfo creation for rpm >= 4.14.
%undefine _debugsource_packages
%undefine _debuginfo_subpackages

# -*- rpm-spec -*-
BuildRoot:      %_topdir/video-simili-duplicate-cleaner-1.13.0L-Linux
Summary:        A tool to find and remove duplicate or similar video files.
Name:           video-simili-duplicate-cleaner
Version:        1.13.0L
Release:        1
License:        unknown
Group:          unknown
Vendor:         EldrinSMP

Url: https://github.com/eldrinsmp/video-simili-duplicate-cleaner
Requires: qt6-qtbase-gui, opencv, ffmpeg-libs












Prefix: /usr





%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename video-simili-duplicate-cleaner-1.13.0L-Linux.rpm
%define _unpackaged_files_terminate_build 0





%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.


# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
mv $RPM_BUILD_ROOT %_topdir/tmpBBroot

%install
if [ -e $RPM_BUILD_ROOT ];
then
  rm -rf $RPM_BUILD_ROOT
fi
mv %_topdir/tmpBBroot $RPM_BUILD_ROOT



%clean








%files
%defattr(-,root,root,-)
/usr/bin/video-simili-duplicate-cleaner




%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 1.13.0L-1
  Generated by CPack RPM (no Changelog file were provided)


