// This file is autogenerated. Changes will be overwritten.
#include "VJIZ3MDCXP/moc_comparison.cpp"
#include "VJIZ3MDCXP/moc_mainwindow.cpp"
#include "VJIZ3MDCXP/moc_prefs.cpp"
#include "VJIZ3MDCXP/moc_video.cpp"
#include "VJIZ3MDCXP/moc_videoprocessingpool.cpp"
