# .github/workflows/build-container.yml
name: Build and Push Arch ARM Container

# This workflow is triggered manually
on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Arch ARM Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permission to write to the GitHub Container Registry

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          # Convert repository name to lowercase for the tag
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}/archlinux-arm:latest" | tr '[:upper:]' '[:lower:]')

          # Build and push the image using the lowercase name
          docker build --platform linux/arm64 -t $IMAGE_NAME .
          docker push $IMAGE_NAME
