# .github/workflows/build-container.yml
name: Build and Push Arch ARM Build-Ready Container

on:
  workflow_dispatch: # Run this manually when you need to update the build image

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Arch ARM Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Dockerfile for Build-Ready Image
        run: |
          echo "--- Downloading Arch Linux ARM rootfs ---"
          wget -q http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz

          echo "--- Creating Dockerfile ---"
          cat <<EOF > Dockerfile
          FROM scratch
          ADD ArchLinuxARM-aarch64-latest.tar.gz /

          # CRITICAL FIX: Initialize pacman keyring before updating.
          # This prevents the build from hanging.
          RUN pacman-key --init && \
              pacman-key --populate archlinuxarm && \
              pacman -Syu --noconfirm && \
              pacman -S --noconfirm --needed base-devel cmake git qt6-base opencv ffmpeg

          CMD ["/bin/bash"]
          EOF

      - name: Build and Push Build-Ready Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/vsdc-archlinux-arm-builder:latest"
          echo "Building and pushing image: $IMAGE_NAME"
          # Build and push for ARM64 platform
          docker buildx build --platform linux/arm64 -t $IMAGE_NAME . --push
