# Workflow name
name: VSDC Linux Multi-Arch Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v3

    - name: Define Directory Paths
      id: dirs
      run: |
        echo "source-dir=${{ github.workspace }}/QtProject_Linux" >> "$GITHUB_OUTPUT"
        echo "build-dir=${{ github.workspace }}/QtProject_Linux/build/release" >> "$GITHUB_OUTPUT"
        echo "package-dir=${{ github.workspace }}/release-files" >> "$GITHUB_OUTPUT"

    # FIX #1: INSTALL THE ARM CROSS-COMPILER
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential cmake pkg-config rpm libfuse2 libgl-dev \
          qt6-base-dev libopencv-dev libavformat-dev libavcodec-dev \
          libavutil-dev libswscale-dev \
          g++-aarch64-linux-gnu # <-- Add the cross-compiler

    # FIX #1: USE THE ARM CROSS-COMPILER
    - name: Configure CMake
      run: |
        # Use an if statement to select the correct compiler for the architecture
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          export CXX=aarch64-linux-gnu-g++
        fi

        cmake -S ${{ steps.dirs.outputs.source-dir }} \
              -B ${{ steps.dirs.outputs.build-dir }} \
              -DCMAKE_CXX_COMPILER=$CXX \
              -DCMAKE_BUILD_TYPE=Release \
              -DCPACK_OUTPUT_FILE_PREFIX=${{ steps.dirs.outputs.package-dir }}

    - name: Build Project
      run: cmake --build ${{ steps.dirs.outputs.build-dir }}

    - name: Generate DEB and RPM Packages
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: cpack

    - name: Create Portable Bundle
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        /home/runner/work/video-simili-duplicate-cleaner/video-simili-duplicate-cleaner/linuxdeployqt-continuous-x86_64.AppImage \
          ./video-simili-duplicate-cleaner -bundle-non-qt-libs -qmake=/usr/lib/qt6/bin/qmake

    - name: Assemble Portable Directory and Archive
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        mkdir VSDC_Portable
        mv lib/ plugins/ doc/ qt.conf AppRun video-simili-duplicate-cleaner VSDC_Portable/
        VERSION=$(grep 'set(CPACK_PACKAGE_VERSION' ${{ steps.dirs.outputs.source-dir }}/CMakeLists.txt | sed -E 's/.*"(.+)".*/\1/')
        tar -czvf ${{ steps.dirs.outputs.package-dir }}/vsdc-portable-${VERSION}-${{ matrix.arch }}.tar.gz VSDC_Portable/

    # FIX #2: COPY RESOURCES TO THE CORRECT LOCATIONS
    - name: Copy Resources for AppImage
      run: |
        # Copy the .desktop file to the root of the bundle
        cp ${{ github.workspace }}/QtProject_Linux/usr/share/applications/video-simili-duplicate-cleaner.desktop ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/
        # Copy the icon file (named to match the .desktop file's Icon entry) to the root of the bundle
        cp ${{ github.workspace }}/QtProject_Linux/usr/share/icons/hicolor/256x256/apps/video-simili-duplicate-cleaner.png ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/video-simili-duplicate-cleaner.png

    - name: Create AppImage
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        /home/runner/work/video-simili-duplicate-cleaner/video-simili-duplicate-cleaner/linuxdeployqt-continuous-x86_64.AppImage \
          ./VSDC_Portable/video-simili-duplicate-cleaner -appimage -qmake=/usr/lib/qt6/bin/qmake

    - name: Upload Packages to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.dirs.outputs.package-dir }}/*.{deb,rpm,tar.gz}
          ${{ steps.dirs.outputs.build-dir }}/*.AppImage
