# Workflow name
name: VSDC Linux Multi-Arch Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # JOB 1: NATIVE x86_64 BUILD (This job is unchanged and works)
  build_x86_64:
    name: Build for x86_64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download linuxdeployqt
        run: |
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      - name: Define Directory Paths
        id: dirs
        run: |
          echo "source-dir=${{ github.workspace }}/QtProject_Linux" >> "$GITHUB_OUTPUT"
          echo "build-dir=${{ github.workspace }}/QtProject_Linux/build/release" >> "$GITHUB_OUTPUT"
          echo "package-dir=${{ github.workspace }}/release-files" >> "$GITHUB_OUTPUT"
      - name: Install x86_64 Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake pkg-config rpm libfuse2 libgl-dev \
            qt6-base-dev libopencv-dev libavformat-dev libavcodec-dev \
            libavutil-dev libswscale-dev
      - name: Configure CMake
        run: |
          cmake -S ${{ steps.dirs.outputs.source-dir }} -B ${{ steps.dirs.outputs.build-dir }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_OUTPUT_FILE_PREFIX=${{ steps.dirs.outputs.package-dir }}
      - name: Build Project
        run: cmake --build ${{ steps.dirs.outputs.build-dir }}
      - name: Generate Packages
        working-directory: ${{ steps.dirs.outputs.build-dir }}
        run: cpack
      - name: Assemble and Archive Portable Bundle
        working-directory: ${{ steps.dirs.outputs.build-dir }}
        run: |
          mkdir VSDC_Portable
          mv lib/ plugins/ doc/ qt.conf AppRun video-simili-duplicate-cleaner VSDC_Portable/
          VERSION=$(grep 'set(CPACK_PACKAGE_VERSION' ${{ steps.dirs.outputs.source-dir }}/CMakeLists.txt | sed -E 's/.*"(.+)".*/\1/')
          tar -czvf ${{ steps.dirs.outputs.package-dir }}/vsdc-portable-${VERSION}-x86_64.tar.gz VSDC_Portable/
      - name: Copy Resources for AppImage
        run: |
          cp ${{ steps.dirs.outputs.source-dir }}/usr/share/applications/video-simili-duplicate-cleaner.desktop ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/
          cp ${{ steps.dirs.outputs.source-dir }}/usr/share/icons/hicolor/256x256/apps/video-simili-duplicate-cleaner.png ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/video-simili-duplicate-cleaner.png
      - name: Create AppImage
        working-directory: ${{ steps.dirs.outputs.build-dir }}
        run: |
          ${{ github.workspace }}/linuxdeployqt-continuous-x86_64.AppImage \
            ./VSDC_Portable/video-simili-duplicate-cleaner -appimage -qmake=/usr/lib/qt6/bin/qmake
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages-x86_64
          path: |
            ${{ steps.dirs.outputs.package-dir }}/*.{deb,rpm,tar.gz}
            ${{ steps.dirs.outputs.build-dir }}/*.AppImage

  # JOB 2: CONTAINERIZED aarch64 BUILD (This is the new approach)
  build_aarch64:
    name: Build for aarch64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build in ARM64 Container
        # This action runs all subsequent commands inside an arm64 Ubuntu container
        uses: docker/run-a-robot-action@v1
        with:
          image: ubuntu:22.04
          run: |
            # 1. Install all dependencies. 'apt-get' now works natively for arm64.
            apt-get update
            apt-get install -y --no-install-recommends \
              build-essential cmake pkg-config rpm libfuse2 libgl-dev \
              qt6-base-dev libopencv-dev libavformat-dev libavcodec-dev \
              libavutil-dev libswscale-dev git wget

            # 2. Configure CMake. No toolchain file is needed.
            cmake -S QtProject_Linux -B QtProject_Linux/build/release \
              -DCMAKE_BUILD_TYPE=Release \
              -DCPACK_OUTPUT_FILE_PREFIX=release-files

            # 3. Build the project.
            cmake --build QtProject_Linux/build/release

            # 4. Generate the deb/rpm packages.
            cd QtProject_Linux/build/release && cpack && cd ../../../

            # 5. Download and run linuxdeployqt.
            wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
            chmod a+x linuxdeployqt-continuous-x86_64.AppImage
            ./linuxdeployqt-continuous-x86_64.AppImage \
              QtProject_Linux/build/release/video-simili-duplicate-cleaner -bundle-non-qt-libs -qmake=/usr/bin/qmake

            # 6. Assemble the portable bundle.
            cd QtProject_Linux/build/release
            mkdir VSDC_Portable
            mv lib/ plugins/ doc/ qt.conf AppRun video-simili-duplicate-cleaner VSDC_Portable/

            # 7. Copy resources.
            cp ../usr/share/applications/video-simili-duplicate-cleaner.desktop VSDC_Portable/
            cp ../usr/share/icons/hicolor/256x256/apps/video-simili-duplicate-cleaner.png VSDC_Portable/video-simili-duplicate-cleaner.png

            # 8. Create the AppImage.
            ../../../../linuxdeployqt-continuous-x86_64.AppImage \
              ./VSDC_Portable/video-simili-duplicate-cleaner -appimage -qmake=/usr/bin/qmake

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages-aarch64
          path: |
            release-files/*.{deb,rpm}
            QtProject_Linux/build/release/*.AppImage

  # JOB 3: CREATE RELEASE (This depends on both builds succeeding)
  release:
    name: Create Release
    needs: [build_x86_64, build_aarch64]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            packages-x86_64/*
            packages-aarch64/*
