# Workflow name
name: VSDC Linux Multi-Arch Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU for ARM emulation
      if: matrix.arch == 'aarch64'
      uses: docker/setup-qemu-action@v3

    - name: Define Directory Paths
      id: dirs
      run: |
        echo "source-dir=${{ github.workspace }}/QtProject_Linux" >> "$GITHUB_OUTPUT"
        echo "build-dir=${{ github.workspace }}/QtProject_Linux/build/release" >> "$GITHUB_OUTPUT"
        echo "package-dir=${{ github.workspace }}/release-files" >> "$GITHUB_OUTPUT"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        # If we are building for ARM...
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          # Add the arm64 architecture and install the cross-compiler and ARM libraries.
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake pkg-config rpm libfuse2 libgl-dev \
            g++-aarch64-linux-gnu \
            qt6-base-dev:arm64 libopencv-dev:arm64 libavformat-dev:arm64 \
            libavcodec-dev:arm64 libavutil-dev:arm64 libswscale-dev:arm64
        else
          # Otherwise, for the x86_64 build, install the normal native libraries.
          sudo apt-get install -y \
            build-essential cmake pkg-config rpm libfuse2 libgl-dev \
            qt6-base-dev libopencv-dev libavformat-dev libavcodec-dev \
            libavutil-dev libswscale-dev
        fi

    - name: Create ARM64 Toolchain File
      # This step only runs for the aarch64 build.
      if: matrix.arch == 'aarch64'
      run: |
        cat <<EOF > ${{ github.workspace }}/arm64.toolchain.cmake
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_SYSTEM_PROCESSOR aarch64)
        set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
        set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
        set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
        set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
        EOF

    - name: Configure CMake
      run: |
        # Start with default options
        CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release -DCPACK_OUTPUT_FILE_PREFIX=${{ steps.dirs.outputs.package-dir }}"
        # If we're on the ARM build, add the toolchain file to the options.
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/arm64.toolchain.cmake"
        fi
        # Run cmake with the correct arguments for the current architecture.
        cmake -S ${{ steps.dirs.outputs.source-dir }} -B ${{ steps.dirs.outputs.build-dir }} $CMAKE_ARGS

    # --- THE REST OF THE WORKFLOW REMAINS THE SAME ---

    - name: Build Project
      run: cmake --build ${{ steps.dirs.outputs.build-dir }}

    - name: Generate DEB and RPM Packages
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: cpack

    - name: Create Portable Bundle
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        /home/runner/work/video-simili-duplicate-cleaner/video-simili-duplicate-cleaner/linuxdeployqt-continuous-x86_64.AppImage \
          ./video-simili-duplicate-cleaner -bundle-non-qt-libs -qmake=/usr/lib/qt6/bin/qmake

    - name: Assemble Portable Directory and Archive
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        mkdir VSDC_Portable
        mv lib/ plugins/ doc/ qt.conf AppRun video-simili-duplicate-cleaner VSDC_Portable/
        VERSION=$(grep 'set(CPACK_PACKAGE_VERSION' ${{ steps.dirs.outputs.source-dir }}/CMakeLists.txt | sed -E 's/.*"(.+)".*/\1/')
        tar -czvf ${{ steps.dirs.outputs.package-dir }}/vsdc-portable-${VERSION}-${{ matrix.arch }}.tar.gz VSDC_Portable/

    - name: Copy Resources for AppImage
      run: |
        cp ${{ github.workspace }}/QtProject_Linux/usr/share/applications/video-simili-duplicate-cleaner.desktop ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/
        cp ${{ github.workspace }}/QtProject_Linux/usr/share/icons/hicolor/256x256/apps/video-simili-duplicate-cleaner.png ${{ steps.dirs.outputs.build-dir }}/VSDC_Portable/video-simili-duplicate-cleaner.png

    - name: Create AppImage
      working-directory: ${{ steps.dirs.outputs.build-dir }}
      run: |
        /home/runner/work/video-simili-duplicate-cleaner/video-simili-duplicate-cleaner/linuxdeployqt-continuous-x86_64.AppImage \
          ./VSDC_Portable/video-simili-duplicate-cleaner -appimage -qmake=/usr/lib/qt6/bin/qmake

    - name: Upload Packages to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ steps.dirs.outputs.package-dir }}/*.{deb,rpm,tar.gz}
          ${{ steps.dirs.outputs.build-dir }}/*.AppImage
